<?php

declare(strict_types=1);

/**
 * @var string      $secret
 * @var string      $provisioningUri
 * @var string      $csrfToken
 * @var string|null $flashSuccess
 * @var string|null $flashError
 */
$templateVars    = get_defined_vars();
$secret          = (string) ($templateVars['secret'] ?? '');
$provisioningUri = (string) ($templateVars['provisioningUri'] ?? '');
$csrfToken       = (string) ($templateVars['csrfToken'] ?? '');
$flashSuccess    = isset($templateVars['flashSuccess']) ? (string) $templateVars['flashSuccess'] : null;
$flashError      = isset($templateVars['flashError']) ? (string) $templateVars['flashError'] : null;
$csrfVal         = htmlspecialchars($csrfToken, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
$secretVal       = htmlspecialchars($secret, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');

$title = 'Two-Factor Authentication (2FA) — PHP-BindManager';
?>
<?php ob_start(); ?>

<div class="pbm-page-heading">
    <div>
        <h1><i class="fa-solid fa-mobile-screen-button me-2"></i>Two-Factor Authentication (TOTP)</h1>
        <p class="pbm-muted">Secure your administrator login with an authenticator app (RFC 6238).</p>
    </div>
    <a href="/profile" class="pbm-btn pbm-btn-secondary">
        <i class="fa-solid fa-arrow-left me-1"></i>Back to Profile
    </a>
</div>

<?php if ($flashSuccess !== null && $flashSuccess !== '') : ?>
    <div class="pbm-alert pbm-alert-success" role="alert">
        <i class="fa-solid fa-circle-check me-2"></i>
        <?= htmlspecialchars($flashSuccess, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8') ?>
    </div>
<?php endif; ?>
<?php if ($flashError !== null && $flashError !== '') : ?>
    <div class="pbm-alert pbm-alert-error" role="alert">
        <i class="fa-solid fa-circle-xmark me-2"></i>
        <?= htmlspecialchars($flashError, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8') ?>
    </div>
<?php endif; ?>

<div class="pbm-card" style="max-width:580px;">
    <div class="pbm-card-header"><i class="fa-solid fa-key me-2"></i>Configure Authenticator App</div>
    <p style="font-size:0.875rem;color:var(--pbm-muted);margin-bottom:16px;">
        1. Open your authenticator app (Google Authenticator, Microsoft Authenticator, Authy, or 1Password).<br>
        2. Enter the secret key below manually or use the provisioning URI.<br>
        3. Enter the 6-digit security code generated by your app to verify setup.
    </p>

    <div class="pbm-form-group">
        <label class="pbm-label">Secret Key</label>
        <code style="display:block;padding:12px;background:var(--pbm-bg);border:1px solid var(--pbm-border);
                     border-radius:var(--pbm-radius);font-size:1.1rem;letter-spacing:2px;text-align:center;">
            <?= htmlspecialchars($secret, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8') ?>
        </code>
    </div>

    <form method="post" action="/profile/totp" style="margin-top:20px;">
        <input type="hidden" name="_csrf_token" value="<?= $csrfVal ?>">
        <input type="hidden" name="secret" value="<?= $secretVal ?>">
        <div class="pbm-form-group">
            <label class="pbm-label" for="totp-code">Verification Code <span class="pbm-required">*</span></label>
            <input id="totp-code" type="text" name="code" class="pbm-input" required
                   placeholder="123456" maxlength="6" pattern="[0-9]{6}" autocomplete="one-time-code"
                   style="font-size:1.2rem;letter-spacing:4px;text-align:center;max-width:200px;">
        </div>
        <div style="display:flex;gap:12px;margin-top:16px;">
            <button type="submit" class="pbm-btn">
                <i class="fa-solid fa-shield-check me-1"></i>Verify &amp; Enable 2FA
            </button>
            <a href="/profile" class="pbm-btn pbm-btn-secondary">Cancel</a>
        </div>
    </form>
</div>

<?php
$content = ob_get_clean();
require_once __DIR__ . '/../layouts/app.php';
